export const homePageData = {
  title: "",
  headline: "📚 Welcome to the Magic Library (မှော်ဝင် စာကြည့်တိုက်)",
  summary: "Explore interactive e-books with hands-on activities. Every chapter is a magical journey of learning.",
  featureHtml:
    "<p><strong>Read Like a Book:</strong> Each chapter feels like flipping through pages in a magical book.</p>" +
    "<p><strong>Interactive Activities:</strong> Quizzes, code exams, and engaging lessons keep you immersed.</p>" +
    "<p><strong>Flexible Content:</strong> Update content without touching code — just edit the data files.</p>",
  callToAction: "Start exploring your first magical book",
  style: {
    main: {
      backgroundColor: "#f8fafc",
      backgroundGradientStart: "#f8fafc",
      backgroundGradientEnd: "#eef2f7",
      useGradient: true,
      color: "#0f172a",
      fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    },
    topMenu: {
      backgroundColor: "rgba(255, 255, 255, 0.96)",
      backgroundColorGradientStart: "rgba(255, 255, 255, 0.96)",
      backgroundColorGradientEnd: "rgba(245, 245, 245, 0.96)",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      borderBottomColor: "#e2e8f0",
      logoBackgroundColor: "#0f172a",
      logoBackgroundColorGradientStart: "#0f172a",
      logoBackgroundColorGradientEnd: "#1e293b",
      useLogoBackgroundColorGradient: false,
      logoColor: "#ffffff",
    },
    buttons: {
      primaryBackgroundColor: "#0f172a",
      primaryBackgroundColorGradientStart: "#0f172a",
      primaryBackgroundColorGradientEnd: "#1e293b",
      usePrimaryBackgroundColorGradient: false,
      primaryColor: "#ffffff",
      secondaryBackgroundColor: "#e2e8f0",
      secondaryBackgroundColorGradientStart: "#e2e8f0",
      secondaryBackgroundColorGradientEnd: "#cbd5e1",
      useSecondaryBackgroundColorGradient: false,
      secondaryColor: "#334155",
    },
    bookshelf: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      borderColor: "#e2e8f0",
    },
    tabs: {
      backgroundColor: "#e2e8f0",
      backgroundColorGradientStart: "#e2e8f0",
      backgroundColorGradientEnd: "#cbd5e1",
      useBackgroundColorGradient: false,
      color: "#334155",
      activeBackgroundColor: "#0f172a",
      activeBackgroundColorGradientStart: "#0f172a",
      activeBackgroundColorGradientEnd: "#1e293b",
      useActiveBackgroundColorGradient: false,
      activeColor: "#ffffff",
    },
    wizardTopInfo: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientMiddle: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      borderBottomColor: "#e2e8f0",
      chapterLabelText: "CHAPTER",
      chapterLabelColor: "#64748b",
      chapterLabelFontSize: 10,
      chapterLabelFontWeight: "700",
      chapterNumberFontSize: 24,
      chapterNumberFontWeight: "700",
      chapterNumberColor: "#0f172a",
      chapterNumberBackgroundColor: "#ffffff",
      chapterNumberBackgroundColorGradientStart: "#ffffff",
      chapterNumberBackgroundColorGradientMiddle: "#ffffff",
      chapterNumberBackgroundColorGradientEnd: "#ffffff",
      chapterNumberUseBackgroundColorGradient: false,
      chapterTitleFontSize: 20,
      chapterTitleFontWeight: "700",
      chapterTitleColor: "#0f172a",
      bookNameFontSize: 16,
      bookNameFontWeight: "700",
      bookNameColor: "#0f172a",
      descriptionBackgroundColor: "#ffffff",
      descriptionColor: "#64748b",
      descriptionFontSize: 16,
      descriptionFontWeight: "normal",
      descriptionLineHeight: 1.6,
      descriptionPaddingTop: 16,
      descriptionPaddingBottom: 16,
    },
    wizardWorkspace: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientMiddle: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      panelBackgroundColor: "#ffffff",
      panelBackgroundColorGradientStart: "#ffffff",
      panelBackgroundColorGradientEnd: "#f8fafc",
      usePanelBackgroundColorGradient: false,
      panelBorderColor: "#e2e8f0",
    },
    wizardButtons: {
      backgroundColor: "#e2e8f0",
      backgroundColorGradientStart: "#e2e8f0",
      backgroundColorGradientEnd: "#cbd5e1",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      hoverBackgroundColor: "#cbd5e1",
      hoverBackgroundColorGradientStart: "#cbd5e1",
      hoverBackgroundColorGradientEnd: "#94a3b8",
      useHoverBackgroundColorGradient: false,
      fontSize: 12,
      fontWeight: "700",
    },
    emptyBook: {
      title: "Coming soon",
      titleFontSize: 24,
      titleFontWeight: "bold",
      titleColor: "#0f172a",
      titlePosition: "center-center",
      coverColorStart: "#f1f5f9",
      coverColorMiddle: "#f1f5f9",
      coverColorEnd: "#f1f5f9",
    },
  },
};
