export const homePageData = {
  title: "",
  headline: "📚 Welcome to the Magic Library (မှော်ဝင် စာကြည့်တိုက်)",
  summary: "Explore interactive e-books with hands-on activities. Every page is a magical journey of learning.",
  featureHtml:
    "<p><strong>Read Like a Book:</strong> Each page feels like flipping through pages in a magical book.</p>" +
    "<p><strong>Interactive Activities:</strong> Quizzes, code exams, and engaging lessons keep you immersed.</p>" +
    "<p><strong>Flexible Content:</strong> Update content without touching code — just edit the data files.</p>",
  callToAction: "Start exploring your first magical book",
  style: {
    main: {
      backgroundColor: "#f8fafc",
      backgroundGradientStart: "#f8fafc",
      backgroundGradientMiddle: "#f8fafc",
      backgroundGradientEnd: "#eef2f7",
      useGradient: true,
      color: "#0f172a",
      fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    },
    topMenu: {
      backgroundColor: "rgba(255, 255, 255, 0.96)",
      backgroundColorGradientStart: "rgba(255, 255, 255, 0.96)",
      backgroundColorGradientMiddle: "rgba(255, 255, 255, 0.96)",
      backgroundColorGradientEnd: "rgba(245, 245, 245, 0.96)",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      borderBottomColor: "#e2e8f0",
      logoBackgroundColor: "#0f172a",
      logoBackgroundColorGradientStart: "#0f172a",
      logoBackgroundColorGradientMiddle: "#0f172a",
      logoBackgroundColorGradientEnd: "#1e293b",
      useLogoBackgroundColorGradient: false,
      logoColor: "#ffffff",
      logoFontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
      logoFontWeight: "700",
      logoFontSize: "18px",
    },
    buttons: {
      primaryBackgroundColor: "#0f172a",
      primaryBackgroundColorGradientStart: "#0f172a",
      primaryBackgroundColorGradientMiddle: "#0f172a",
      primaryBackgroundColorGradientEnd: "#1e293b",
      usePrimaryBackgroundColorGradient: false,
      primaryColor: "#ffffff",
      primaryFontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
      primaryFontWeight: "700",
      secondaryBackgroundColor: "#e2e8f0",
      secondaryBackgroundColorGradientStart: "#e2e8f0",
      secondaryBackgroundColorGradientMiddle: "#e2e8f0",
      secondaryBackgroundColorGradientEnd: "#cbd5e1",
      useSecondaryBackgroundColorGradient: false,
      secondaryColor: "#334155",
      secondaryFontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
      secondaryFontWeight: "600",
    },
    bookshelf: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientMiddle: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      borderColor: "#e2e8f0",
    },
    tabs: {
      backgroundColor: "#e2e8f0",
      backgroundColorGradientStart: "#e2e8f0",
      backgroundColorGradientMiddle: "#e2e8f0",
      backgroundColorGradientEnd: "#cbd5e1",
      useBackgroundColorGradient: false,
      color: "#334155",
      fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
      fontWeight: "600",
      activeBackgroundColor: "#0f172a",
      activeBackgroundColorGradientStart: "#0f172a",
      activeBackgroundColorGradientMiddle: "#0f172a",
      activeBackgroundColorGradientEnd: "#1e293b",
      useActiveBackgroundColorGradient: false,
      activeColor: "#ffffff",
    },
    hero: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientMiddle: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      eyebrowColor: "#6b7280",
      titleColor: "#0f172a",
      descriptionColor: "#475569",
      fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
    },
    wizardTopInfo: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientMiddle: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      borderBottomColor: "#e2e8f0",
      chapterLabelText: "Page",
      chapterLabelColor: "#64748b",
      chapterLabelFontSize: 10,
      chapterLabelFontWeight: "700",
      chapterNumberFontSize: 24,
      chapterNumberFontWeight: "700",
      chapterNumberColor: "#0f172a",
      chapterNumberBackgroundColor: "#ffffff",
      chapterNumberBackgroundColorGradientStart: "#ffffff",
      chapterNumberBackgroundColorGradientMiddle: "#ffffff",
      chapterNumberBackgroundColorGradientEnd: "#ffffff",
      chapterNumberUseBackgroundColorGradient: false,
      chapterTitleFontSize: 20,
      chapterTitleFontWeight: "700",
      chapterTitleColor: "#0f172a",
      bookNameFontSize: 16,
      bookNameFontWeight: "700",
      bookNameColor: "#0f172a",
      descriptionBackgroundColor: "#ffffff",
      descriptionBackgroundColorGradientStart: "#ffffff",
      descriptionBackgroundColorGradientMiddle: "#ffffff",
      descriptionBackgroundColorGradientEnd: "#f8fafc",
      descriptionColor: "#64748b",
      descriptionFontSize: 16,
      descriptionFontWeight: "normal",
      descriptionLineHeight: 1.6,
      descriptionPaddingTop: 16,
      descriptionPaddingBottom: 16,
      descriptionPaddingLeft: 12,
      descriptionPaddingRight: 12,
      navButton: {
        backgroundColor: "#e2e8f0",
        border: "none",
        color: "#0f172a",
        disabledColor: "#94a3b8"
      },
      homeButton: {
        backgroundColor: "#e2e8f0",
        border: "none",
        color: "#0f172a"
      },
      chapterLabel: {
        backgroundColor: "rgba(15,23,42,0.05)",
        border: "none",
        color: "#64748b",
        fontSize: 14,
        fontWeight: "700"
      }
    },
    wizardWorkspace: {
      backgroundColor: "#ffffff",
      backgroundColorGradientStart: "#ffffff",
      backgroundColorGradientMiddle: "#ffffff",
      backgroundColorGradientEnd: "#f8fafc",
      useBackgroundColorGradient: false,
      panelBackgroundColor: "#ffffff",
      panelBackgroundColorGradientStart: "#ffffff",
      panelBackgroundColorGradientMiddle: "#ffffff",
      panelBackgroundColorGradientEnd: "#f8fafc",
      usePanelBackgroundColorGradient: false,
      panelBorderColor: "#e2e8f0",
    },
    wizardButtons: {
      backgroundColor: "#e2e8f0",
      backgroundColorGradientStart: "#e2e8f0",
      backgroundColorGradientMiddle: "#e2e8f0",
      backgroundColorGradientEnd: "#cbd5e1",
      useBackgroundColorGradient: false,
      color: "#0f172a",
      hoverBackgroundColor: "#cbd5e1",
      hoverBackgroundColorGradientStart: "#cbd5e1",
      hoverBackgroundColorGradientMiddle: "#cbd5e1",
      hoverBackgroundColorGradientEnd: "#94a3b8",
      useHoverBackgroundColorGradient: false,
      fontSize: 12,
      fontWeight: "700",
    },
    emptyBook: {
      title: "Coming soon",
      titleFontSize: 24,
      titleFontWeight: "bold",
      titleColor: "#0f172a",
      titlePosition: "center-center",
      titleTextAlign: "center",
      titleAlignment: "center",
      coverColorStart: "#f1f5f9",
      coverColorMiddle: "#f1f5f9",
      coverColorEnd: "#f1f5f9",
      coverWidth: 100,
      coverHeight: 150,
    },
    bookshelfTheme: {
      selectedTheme: "space",
      availableThemes: ["space", "dinosaur", "ocean", "gradient", "custom"],
    },
    heroTheme: {
      selectedTheme: "space",
      availableThemes: ["space", "ocean", "dinosaur", "custom"],
    },
    themePresets: {
      space: {
        backgroundColor: "#0f0c29",
        backgroundColorGradientStart: "#0f0c29",
        backgroundColorGradientMiddle: "#302b63",
        backgroundColorGradientEnd: "#24243e",
        useBackgroundColorGradient: true,
        borderColor: "rgba(255,255,255,0.1)",
        tabs: {
          backgroundColor: "rgba(255,255,255,0.1)",
          backgroundColorGradientStart: "rgba(255,255,255,0.1)",
          backgroundColorGradientMiddle: "rgba(255,255,255,0.15)",
          backgroundColorGradientEnd: "rgba(255,255,255,0.1)",
          useBackgroundColorGradient: true,
          color: "#e0e7ff",
          activeBackgroundColor: "#667eea",
          activeBackgroundColorGradientStart: "#667eea",
          activeBackgroundColorGradientMiddle: "#764ba2",
          activeBackgroundColorGradientEnd: "#667eea",
          useActiveBackgroundColorGradient: true,
          activeColor: "#ffffff",
        },
        hero: {
          backgroundColor: "rgba(255,255,255,0.05)",
          backgroundColorGradientStart: "rgba(255,255,255,0.05)",
          backgroundColorGradientMiddle: "rgba(255,255,255,0.08)",
          backgroundColorGradientEnd: "rgba(255,255,255,0.05)",
          useBackgroundColorGradient: true,
          color: "#e0e7ff",
          eyebrowColor: "#a78bfa",
          titleColor: "#7de3f4",
          descriptionColor: "#c4b5fd",
        },
      },
      dinosaur: {
        backgroundColor: "#2d2416",
        backgroundColorGradientStart: "#2d2416",
        backgroundColorGradientMiddle: "#4a3c2e",
        backgroundColorGradientEnd: "#3d3228",
        useBackgroundColorGradient: true,
        borderColor: "rgba(139,90,43,0.3)",
        tabs: {
          backgroundColor: "rgba(139,90,43,0.2)",
          backgroundColorGradientStart: "rgba(139,90,43,0.2)",
          backgroundColorGradientMiddle: "rgba(160,110,60,0.25)",
          backgroundColorGradientEnd: "rgba(139,90,43,0.2)",
          useBackgroundColorGradient: true,
          color: "#e8d4b8",
          activeBackgroundColor: "#8b5a2b",
          activeBackgroundColorGradientStart: "#8b5a2b",
          activeBackgroundColorGradientMiddle: "#a0522d",
          activeBackgroundColorGradientEnd: "#8b5a2b",
          useActiveBackgroundColorGradient: true,
          activeColor: "#fff8e7",
        },
        hero: {
          backgroundColor: "rgba(139,90,43,0.1)",
          backgroundColorGradientStart: "rgba(139,90,43,0.1)",
          backgroundColorGradientMiddle: "rgba(160,110,60,0.15)",
          backgroundColorGradientEnd: "rgba(139,90,43,0.1)",
          useBackgroundColorGradient: true,
          color: "#e8d4b8",
          eyebrowColor: "#d4a574",
          titleColor: "#ffb347",
          descriptionColor: "#c9a86c",
        },
      },
      ocean: {
        backgroundColor: "#0a192f",
        backgroundColorGradientStart: "#0a192f",
        backgroundColorGradientMiddle: "#112240",
        backgroundColorGradientEnd: "#0d1b2a",
        useBackgroundColorGradient: true,
        borderColor: "rgba(100,200,255,0.2)",
        tabs: {
          backgroundColor: "rgba(100,200,255,0.1)",
          backgroundColorGradientStart: "rgba(100,200,255,0.1)",
          backgroundColorGradientMiddle: "rgba(150,220,255,0.15)",
          backgroundColorGradientEnd: "rgba(100,200,255,0.1)",
          useBackgroundColorGradient: true,
          color: "#b8d4e8",
          activeBackgroundColor: "#00b4d8",
          activeBackgroundColorGradientStart: "#00b4d8",
          activeBackgroundColorGradientMiddle: "#0096c7",
          activeBackgroundColorGradientEnd: "#00b4d8",
          useActiveBackgroundColorGradient: true,
          activeColor: "#ffffff",
        },
        hero: {
          backgroundColor: "rgba(0,180,216,0.08)",
          backgroundColorGradientStart: "rgba(0,180,216,0.08)",
          backgroundColorGradientMiddle: "rgba(0,150,199,0.12)",
          backgroundColorGradientEnd: "rgba(0,180,216,0.08)",
          useBackgroundColorGradient: true,
          color: "#b8d4e8",
          eyebrowColor: "#48cae4",
          titleColor: "#90e0ef",
          descriptionColor: "#ade8f4",
        },
      },
      gradient: {
        backgroundColor: "#f8fafc",
        backgroundColorGradientStart: "#f8fafc",
        backgroundColorGradientMiddle: "#e2e8f0",
        backgroundColorGradientEnd: "#f1f5f9",
        useBackgroundColorGradient: true,
        borderColor: "#e2e8f0",
        tabs: {
          backgroundColor: "#e2e8f0",
          backgroundColorGradientStart: "#e2e8f0",
          backgroundColorGradientMiddle: "#cbd5e1",
          backgroundColorGradientEnd: "#e2e8f0",
          useBackgroundColorGradient: true,
          color: "#334155",
          activeBackgroundColor: "#0f172a",
          activeBackgroundColorGradientStart: "#0f172a",
          activeBackgroundColorGradientMiddle: "#1e293b",
          activeBackgroundColorGradientEnd: "#0f172a",
          useActiveBackgroundColorGradient: true,
          activeColor: "#ffffff",
        },
        hero: {
          backgroundColor: "#ffffff",
          backgroundColorGradientStart: "#ffffff",
          backgroundColorGradientMiddle: "#f8fafc",
          backgroundColorGradientEnd: "#ffffff",
          useBackgroundColorGradient: true,
          color: "#0f172a",
          eyebrowColor: "#6b7280",
          titleColor: "#0f172a",
          descriptionColor: "#475569",
        },
      },
    },
  },
};
